export const projects = [
  {
    id: 1,
    year: "2024",
    category: "Fintech",
    industry: "Health",
    title: "Caregivers Hospital",
    description:
      "A User-centered Electronic Medical Record (EMR) System Integrating health maintenance organizations (HMOs)",
    info: "Modern digital health and financial tools are growing rapidly, enabling connected protocols, integrated payment gateways, and streamlined user experiences across global platforms.",
    imageSrc: "/Thumbnail.png",
    link: "#",
  },
  {
    id: 2,
    year: "2025",
    category: "Fintech",
    industry: "Finance",
    title: "Altima",
    description: "A simplified user centered preoder system, aimed at simplifying preoder of smart door handles",
    info: "Modern digital health and financial tools are growing rapidly, enabling connected protocols, integrated payment gateways, and streamlined user experiences across global platforms.",
    imageSrc: "/thumbnail01.png",
    link: "#",
  },

  {
    id: 3,
    year: "2025",
    category: "Fintech",
    industry: "Finance",
    title: "AMD Facility Management",
    description: "A simplified user centered preoder system, aimed at simplifying preoder of smart door handles",
    info: "Modern digital health and financial tools are growing rapidly, enabling connected protocols, integrated payment gateways, and streamlined user experiences across global platforms.",
    imageSrc: "/amd.png",
    link: "#",
  },
  {
    id: 4,
    year: "2025",
    category: "Fintech",
    industry: "Finance",
    title: "Kaduna Electric",
    description: "A simplified user centered preoder system, aimed at simplifying preoder of smart door handles",
    info: "Modern digital health and financial tools are growing rapidly, enabling connected protocols, integrated payment gateways, and streamlined user experiences across global platforms.",
    imageSrc: "/kad.png",
    link: "#",
  },
  {
    id: 5,
    year: "2025",
    category: "Fintech",
    industry: "Finance",
    title: "Chainkeeping",
    description: "A simplified user centered preoder system, aimed at simplifying preoder of smart door handles",
    info: "Modern digital health and financial tools are growing rapidly, enabling connected protocols, integrated payment gateways, and streamlined user experiences across global platforms.",
    imageSrc: "/Dshboard (3).png",
    link: "#",
  },
  // Add more project objects as needed
]
