export const projects = [
  {
    id: 1,
    year: "2024",
    category: "Web 2",
    industry: "Health",
    title: "Caregivers Hospital",
    description:
      "A User-centered Electronic Medical Record (EMR) System Integrating health maintenance organizations (HMOs)",
    info: "The Stacks ecosystem is growing at a bullish pace. With about 10 protocols & communities, 19 partners & integrations, 12 tools and utilities, and about 27 dApps are currently built on the ecosystem. Stacks ecosystem is becoming a significant player in the decentralized market and web3 as a whole.",
    imageSrc: "/Thumbnail.png",
    link: "#",
  },
  {
    id: 2,
    year: "2025",
    category: "Web 3",
    industry: "Finance",
    title: "Altima",
    description: "A simplified user centered preoder system, aimed at simplifying preoder of smart door handles",
    info: "The Stacks ecosystem is growing at a bullish pace. With about 10 protocols & communities, 19 partners & integrations, 12 tools and utilities, and about 27 dApps are currently built on the ecosystem. Stacks ecosystem is becoming a significant player in the decentralized market and web3 as a whole.",
    imageSrc: "/thumbnail01.png",
    link: "#",
  },

  {
    id: 3,
    year: "2025",
    category: "Web 3",
    industry: "Finance",
    title: "AMD Facility Management",
    description: "A simplified user centered preoder system, aimed at simplifying preoder of smart door handles",
    info: "The Stacks ecosystem is growing at a bullish pace. With about 10 protocols & communities, 19 partners & integrations, 12 tools and utilities, and about 27 dApps are currently built on the ecosystem. Stacks ecosystem is becoming a significant player in the decentralized market and web3 as a whole.",
    imageSrc: "/amd.png",
    link: "#",
  },
  {
    id: 4,
    year: "2025",
    category: "Web 3",
    industry: "Finance",
    title: "Kaduna Electric",
    description: "A simplified user centered preoder system, aimed at simplifying preoder of smart door handles",
    info: "The Stacks ecosystem is growing at a bullish pace. With about 10 protocols & communities, 19 partners & integrations, 12 tools and utilities, and about 27 dApps are currently built on the ecosystem. Stacks ecosystem is becoming a significant player in the decentralized market and web3 as a whole.",
    imageSrc: "/kad.png",
    link: "#",
  },
  {
    id: 5,
    year: "2025",
    category: "Web 3",
    industry: "Finance",
    title: "Chainkeeping",
    description: "A simplified user centered preoder system, aimed at simplifying preoder of smart door handles",
    info: "The Stacks ecosystem is growing at a bullish pace. With about 10 protocols & communities, 19 partners & integrations, 12 tools and utilities, and about 27 dApps are currently built on the ecosystem. Stacks ecosystem is becoming a significant player in the decentralized market and web3 as a whole.",
    imageSrc: "/Dshboard (3).png",
    link: "#",
  },
  // Add more project objects as needed
]
